#pragma once

#if PLATFORM_PS4
#include <orbis/Pigletv2VSH.h>
#define GL_QUADS 0x0007
#else
//
// NOTE: Glad is only used for the header, the implementation is not used.
//
#include "glad2.h"
#endif

struct OpenGLFunctions
{
	//
	// OpenGL 1.1+
	//
	PFNGLCLEARPROC Clear;
	PFNGLCLEARCOLORPROC ClearColor;
	PFNGLVIEWPORTPROC Viewport;
	PFNGLGENTEXTURESPROC GenTextures;
	PFNGLTEXIMAGE2DPROC TexImage2D;
	PFNGLTEXPARAMETERIPROC TexParameteri;
	PFNGLBINDTEXTUREPROC BindTexture;
	PFNGLENABLEPROC Enable;
	PFNGLDISABLEPROC Disable;
	PFNGLBLENDFUNCPROC BlendFunc;
	PFNGLDRAWELEMENTSPROC DrawElements;
	PFNGLDRAWARRAYSPROC DrawArrays;

	//
	// OpenGL 1.1 Only
	//
#if PLATFORM_PS4
#else
	PFNGLENABLECLIENTSTATEPROC EnableClientState;
	PFNGLVERTEXPOINTERPROC VertexPointer;
	PFNGLTEXCOORDPOINTERPROC TexCoordPointer;
	PFNGLMATRIXMODEPROC MatrixMode;
	PFNGLLOADIDENTITYPROC LoadIdentity;
	PFNGLORTHOPROC Ortho;
	PFNGLLOADMATRIXFPROC LoadMatrixf;
	PFNGLCOLORPOINTERPROC ColorPointer;
#endif

	//
	// GLES 2.0+
	//
	PFNGLGENBUFFERSPROC GenBuffers;
	PFNGLBINDBUFFERPROC BindBuffer;
	PFNGLBUFFERDATAPROC BufferData;
	PFNGLBUFFERSUBDATAPROC BufferSubData;
	PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer;
	PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray;
	PFNGLCREATESHADERPROC CreateShader;
	PFNGLSHADERSOURCEPROC ShaderSource;
	PFNGLCOMPILESHADERPROC CompileShader;
	PFNGLGETSHADERIVPROC GetShaderiv;
	PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
	PFNGLCREATEPROGRAMPROC CreateProgram;
	PFNGLATTACHSHADERPROC AttachShader;
	PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation;
	PFNGLLINKPROGRAMPROC LinkProgram;
	PFNGLGETPROGRAMIVPROC GetProgramiv;
	PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
	PFNGLUSEPROGRAMPROC UseProgram;
	PFNGLDELETESHADERPROC DeleteShader;
	PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
	PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv;
	PFNGLUNIFORM1FVPROC Uniform1fv;
	PFNGLUNIFORM4FVPROC Uniform4fv;
	PFNGLGENERATEMIPMAPPROC GenerateMipmap;
	PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
	PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
	PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
};
